### ISSUE TITLE
Conversion from poker now issue

### ISSUE THREAD

**Issue by jonathanogrady** [pj4533/PokerNowConvert#10]
11T20:17:26.380Z,160512584638102
"""Will @ mEHnf7cdka"" collected 276 from pot with Two Pair, 4's & 3's (combination: 4♣, 4♠, 3♠, 3♣, Q♦)",2020-11-11T20:17:26.380Z,160512584638101
"""Will @ mEHnf7cdka"" shows a 3♠, 4♣.",2020-11-11T20:17:26.380Z,160512584638100

Comes out as

Will: calls $46.00
*** SHOW DOWN ***
Will: shows [error error 4s 3s 3c Qd] (Two Pair, 4's & 3's)
Will collected $276.00 from pot
*** SUMMARY ***
Total pot: $276.00 | Rake 0
Board: [Js 4s Tc 3c Qd]

Note "error error"

**Comment by pj4533** [comment]
Could you post the raw log for the whole hand?

**Comment by jonathanogrady** [comment]
Thank you so much for your speedy reply! I'm a bit of a novice, so difficult for me to do the exact hand, easier for me to post the log…

**Comment by pj4533** [comment]
Thats what I mean, post the entire log for the hand (or if you'd rather the log for the session). And I'll figure out the issue.

**Comment by jonathanogrady** [comment]
[poker now.txt](https://github.com/pj4533/PokerNowConvert/files/5532552/poker.now.txt)

**Comment by jonathanogrady** [comment]
Much obliged!

**Comment by pj4533** [comment]
k, should be fixed now. That line shouldn't have been in there, I forgot to update shared code when I pushed it a while back.

**Comment by jonathanogrady** [comment]
That's very kind of you indeed! One final question, when I save that converted file to a text file, why is it coming up as unsupported import when I tried to upload it to poker Snowie? That was my ultimate goal! Any insights you can provide gratefully appreciated. Best wishes, Jonathan

**Comment by pj4533** [comment]
Yeah, click on the 'unsupported import' and it will show you the errors for each hand. Looks like PokerSnowie is kinda picky, but I was able to get most hands imported. The primary reason in your case is that your log doesn't have your hole cards so it says 'player not dealt in'. To get your hole cards, you need to download the log at the PokerNow table when you play (so the browser has your cookie, so it knows it is you downloading), then you get your hands for the session & PokerSnowie will do its thing.

**Comment by jonathanogrady** [comment]
That's very helpful! I will be sure to download after I've logged in next time. Very many thanks! Jonathan
