### ISSUE TITLE
Poker analysis

### ISSUE THREAD

**Issue by jonathanogrady** [pj4533/PokerNowConvert#11]
While we're on the subject, have you any advice for good programs which could analyse that game I gave you previously? I don't have the hole cards, but I was hoping that there would be a convenient way for me to analyse the respective player performances. I have a suspicion that one of the players might have had help… Would love to know statistically how well he played.

You've been very kind, so no trouble if it's not an easy question to answer. Just wondering…

Many thanks, Jonathan

**Comment by pj4533** [comment]
I just loaded it real quick into PokerTracker. Can get lots of stats from that (or HoldEm Manager). 

<img width="575" alt="results" src="https://user-images.githubusercontent.com/110283/98994803-633a7280-24fe-11eb-906f-9fb9b96e31e8.png">

I don't know, only thing I'd say is that with everyone playing over 50% of hands, crazy shit is going happen.

**Comment by jonathanogrady** [comment]
Amazing! Thank you!
