### ISSUE TITLE
Action from seated player is ignored

### ISSUE THREAD

**Issue by BigLeBlairski** [pj4533/PokerNowConvert#9]
After importing the converted log into PokerTracker, I noticed all of pots I won are $0.00.  I've attached the converted file, and I can provide you with the excel log if needed. 
[08.29.20 1-2 (Eve 1).txt](https://github.com/pj4533/PokerNowConvert/files/5146443/08.29.20.1-2.Eve.1.txt)

**Comment by BigLeBlairski** [comment]
Here's a notepad file with the raw data from the log. 
[08.29.20 1-2 (Eve 1) raw data.txt](https://github.com/pj4533/PokerNowConvert/files/5146448/08.29.20.1-2.Eve.1.raw.data.txt)

I noticed this has the total pot sizes for the hands I won/lost; whereas the converted version did not.

**Comment by pj4533** [comment]
@BigLeBlairski   Hmmmmmm...for sure some sort of bug in here.   It has something to do with all the sit/reseat craziness that happened before the start of the game.  It looks like that somehow confused the converter into thinking you weren't part of the game, so it didn't put any of your action in the final log.   I'll check into this.  However if you want a quick fix, I was able to convert the log if you delete all the lines from the END of the raw file up to the line that says 'starting hand 1' (basically just remove all the standup/sitback stuff before the game starts).

**Comment by pj4533** [comment]
(Changing name/description to fit bug)

**Comment by pj4533** [comment]
@BigLeBlairski   Ok this is deployed.  I tested with your log and it seems to work.  Lemme know if there are any other issues you see.
